export const TYPES = {
  IMemberAdapter: 'IMemberAdapter',
  INotificationAdapter: 'INotificationAdapter',
  IAccountAdapter: 'IAccountAdapter',
  IFinancialSourceAdapter: 'IFinancialSourceAdapter',
  IChartOfAccountAdapter: 'IChartOfAccountAdapter',
  IFinancialTransactionHeaderAdapter: 'IFinancialTransactionHeaderAdapter',
  IFinancialTransactionAdapter: 'IFinancialTransactionAdapter',
  IIncomeTransactionAdapter: 'IIncomeTransactionAdapter',
  IFundAdapter: 'IFundAdapter',
  IOfferingBatchAdapter: 'IOfferingBatchAdapter',
  IAuthUserAdapter: 'IAuthUserAdapter',
  IMemberRepository: 'IMemberRepository',
  INotificationRepository: 'INotificationRepository',
  IAccountRepository: 'IAccountRepository',
  IFinancialSourceRepository: 'IFinancialSourceRepository',
  IChartOfAccountRepository: 'IChartOfAccountRepository',
  IFinancialTransactionHeaderRepository: 'IFinancialTransactionHeaderRepository',
  IFinancialTransactionRepository: 'IFinancialTransactionRepository',
  IIncomeTransactionRepository: 'IIncomeTransactionRepository',
  IFundRepository: 'IFundRepository',
  IOfferingBatchRepository: 'IOfferingBatchRepository',
  ICategoryAdapter: 'ICategoryAdapter',
  ICategoryRepository: 'ICategoryRepository',
  IUserRepository: 'IUserRepository',
  AuditService: 'AuditService'
};
